[project]
name = "rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "gymnasium>=1.2.2",
    "numpy>=2.3.5",
    "torch>=2.9.1",
    "wandb>=0.23.0",
]
